f <- readLines("scripts/00c_ingest_nrb_real.R")
f <- gsub("MIN_MONTHS_FOR_TS <- 24L", "MIN_MONTHS_FOR_TS <- 36L", f)
writeLines(f, "scripts/00c_ingest_nrb_real.R")

f2 <- readLines("scripts/04_timeseries_structural_break.R")
f2 <- gsub("select_consecutive_block(nrb_ts_all, 24L)", "select_consecutive_block(nrb_ts_all, 36L)", f2)
f2 <- gsub("length(ts_remit) >= 24", "length(ts_remit) >= 36", f2)
f2 <- gsub("min_months = 24L", "min_months = 36L", f2)
f2 <- gsub("select(month, remit_npr_bn, source)", "select(month, remit_npr_bn)", f2)
writeLines(f2, "scripts/04_timeseries_structural_break.R")
cat("Patched to 36-month minimum for STL\n")
